- .drone.yml
Drone build was failing for preprod environment.   Added cmd  to install aws package in preprod and prod environments
> fixed issue for preprod and prod environment to install aws cmd

- .drone.yml
Drone file changes to fix missing aws environment variables for preprod and deeleted volumes that are not being used for preprod and prod ennvironments
> Drone file changes to fix missing aws environment variables for preprod

- ci-cd-resources/subscribe_to_alert_topics.py
Added missing python script file in ci-cd-resources  for operational monitoring subscription
> Added missing python script file in ci-cd-resources

- .drone.yml
Removed hard-coded value for notify-api-key from drone file
> Removed hard-coded value for notify-api-key from drone file

- .drone.yml
- pom.xml
- src/main/resources/application.yml
- src/main/resources/bootstrap.yml
Source secret value from active spring profile in favour of fixed bootstrap.yml value
> Source secret value from active spring profile

- .drone.yml
- pom.xml
https://eaflood.atlassian.net/browse/CAZB-310
> CAZB-310 sonar scan configuration

- pom.xml
- src/main/java/uk/gov/caz/notify/amazonaws/StreamLambdaHandler.java
- src/main/java/uk/gov/caz/notify/controller/ManualDispatchController.java
- src/main/java/uk/gov/caz/notify/dto/SendEmailRequest.java
- src/main/java/uk/gov/caz/notify/messaging/MessagingClient.java
- src/test/java/uk/gov/caz/notify/controller/ManualDispatchControllerTest.java
- src/test/java/uk/gov/caz/notify/dto/SendEmailRequestTest.java
- src/test/java/uk/gov/caz/notify/messaging/MessagingClientTest.java
https://eaflood.atlassian.net/browse/CAZB-311
> CAZB-311 Fix Notify Gateway code issues

- .drone.yml
> Add drone ST steps

- src/main/java/uk/gov/caz/notify/messaging/MessagingClient.java
[Link to CAZSM-14 JIRA Card](https://eaflood.atlassian.net/browse/CAZSM-14)
> [CAZSM-14] Removal of Notify Reference Number from logs

- .drone2.yml
- pom.xml
CAZB-1180 Added drone2.yml file for aws-restructure dev env pipeline
> CAZB-1180 Added drone2.yml file for aws-restructure dev env pipeline

- .drone2.yml
> corrected terraform iac path

- .drone2.yml
> updated deploy pipeline

- .drone2.yml
updated  with aws credentials path secrets
> updated  with aws credentials path secrets

- .drone2.yml
removed projectkey param from sonar scan target
> removed projectkey param from sonar scan target

- .drone2.yml
updated controlled ST environment changes
> updated controlled ST environment changes

- .drone2.yml
- pom.xml
- src/main/java/uk/gov/caz/notify/messaging/MessagingClient.java
- src/test/java/uk/gov/caz/notify/controller/ManualDispatchControllerTest.java
- src/test/java/uk/gov/caz/notify/messaging/MessagingClientTest.java
Update new AWS account ST environment
> Update new AWS account ST environment

- .drone2.yml
- pom.xml
- src/main/java/uk/gov/caz/notify/messaging/MessagingClient.java
- src/test/java/uk/gov/caz/notify/controller/ManualDispatchControllerTest.java
- src/test/java/uk/gov/caz/notify/messaging/MessagingClientTest.java
Update Iac restructure controlled SIT
> Update Iac restructure controlled SIT

- .drone2.yml
- pom.xml
- src/main/java/uk/gov/caz/notify/messaging/MessagingClient.java
- src/test/java/uk/gov/caz/notify/controller/ManualDispatchControllerTest.java
- src/test/java/uk/gov/caz/notify/messaging/MessagingClientTest.java
Promote latest Notify Gateway code to new pre-prod
> Promote latest Notify Gateway code to new pre-prod

- .drone2.yml
- pom.xml
- src/main/java/uk/gov/caz/notify/messaging/MessagingClient.java
- src/test/java/uk/gov/caz/notify/controller/ManualDispatchControllerTest.java
- src/test/java/uk/gov/caz/notify/messaging/MessagingClientTest.java
Refresh Notify Gateway in new Production environment
> Refresh Notify Gateway in new Production environment

- .drone2.yml
Add docker sockets to UAT pipeline
> UAT pipeline fix

- .drone2.yml
> Fix uat package location

- pom.xml
- src/main/java/uk/gov/caz/notify/domain/QueueName.java
- src/main/java/uk/gov/caz/notify/messaging/MessagingClient.java
- src/main/java/uk/gov/caz/notify/service/MessageHandlingService.java
- src/test/java/uk/gov/caz/notify/messaging/MessagingClientTest.java
- src/test/java/uk/gov/caz/notify/service/MessageHandlingServiceTest.java
This PR encompasses the following changes:
- update internal library version
- add DLQ to recognised queue names
- remove `writeValueToString` method call
> [CAZB-3042] add processing for DLQ

- src/main/java/uk/gov/caz/notify/service/MessageHandlingService.java
- src/main/resources/application.yml
Update RC 1.3.0 with externalised SQS wait time
> [CAZB-4051] Externalise SQS message receive wait time (#72)

- .drone2.yml
[CAZB-5004] Add SIT2 pipeline steps (#77)
> [CAZB-5004] Add SIT2 pipeline steps (#77)
